o
fD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\AddModifierTests.csutf-8g
^D:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\AddTests.csutf-8k
bD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\CaptureTests.csutf-8m
dD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\EndOfLineTests.csutf-8i
`D:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\MaybeTests.csutf-8l
cD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\MultipleTests.csutf-8f
]D:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\OrTests.csutf-8k
bD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\OwnUnitTests.csutf-8o
fD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\PerformanceTests.csutf-8v
mD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\Properties\AssemblyInfo.csutf-8i
`D:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\RangeTests.csutf-8r
iD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\RemoveModifierTests.csutf-8q
hD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\RepeatPreviousTest.csutf-8l
cD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\SanatizeTests.csutf-8p
gD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\SomethingButTests.csutf-8m
dD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\SomethingTests.csutf-8o
fD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\StartOfLineTests.csutf-8h
_D:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\ThenTests.csutf-8u
lD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\VerbalExpressionsTests.csutf-8o
fD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\CSharpTest\WithAnyCaseTests.csutf-8q
hD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressions\CommonRegex.csutf-8}
tD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressions\Properties\AssemblyInfo.csutf-8p
gD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressions\RegexCache.csutf-8~
nD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressions\VerbalExpressions.cswindows-1250
vD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\AddModifierTests.csutf-8w
nD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\AddTests.csutf-8{
rD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\CaptureTests.csutf-8}
tD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\EndOfLineTests.csutf-8y
pD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\MaybeTests.csutf-8|
sD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\MultipleTests.csutf-8v
mD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\OrTests.csutf-8
vD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\PerformanceTests.csutf-8Ü
}D:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\Properties\AssemblyInfo.csutf-8y
pD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\RangeTests.csutf-8Ç
yD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\RemoveModifierTests.csutf-8Å
xD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\RepeatPreviousTest.csutf-8|
sD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\SanatizeTests.csutf-8Ä
wD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\SomethingButTests.csutf-8}
tD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\SomethingTests.csutf-8
vD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\StartOfLineTests.csutf-8x
oD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\ThenTests.csutf-8Ö
|D:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\VerbalExpressionsTests.csutf-8
vD:\6.felev\Integracios es ellenorzesi technikak\CSharpVerbalExpressions\VerbalExpressionsUnitTests\WithAnyCaseTests.csutf-8